/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context/index"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Client: { // root type
    id?: number | null; // Int
    name?: string | null; // String
    orders?: Array<NexusGenRootTypes['Order'] | null> | null; // [Order]
    phone?: string | null; // String
  }
  Mutation: {};
  Order: { // root type
    address?: string | null; // String
    dateTime?: string | null; // String
    food?: string | null; // String
    id?: number | null; // Int
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Client: { // field return type
    id: number | null; // Int
    name: string | null; // String
    orders: Array<NexusGenRootTypes['Order'] | null> | null; // [Order]
    phone: string | null; // String
  }
  Mutation: { // field return type
    createClient: NexusGenRootTypes['Client']; // Client!
    deleteClient: NexusGenRootTypes['Client']; // Client!
    updateClient: NexusGenRootTypes['Client']; // Client!
  }
  Order: { // field return type
    address: string | null; // String
    dateTime: string | null; // String
    food: string | null; // String
    id: number | null; // Int
  }
  Query: { // field return type
    queryAllClient: Array<NexusGenRootTypes['Client'] | null>; // [Client]!
    queryOneClient: NexusGenRootTypes['Client']; // Client!
  }
}

export interface NexusGenFieldTypeNames {
  Client: { // field return type name
    id: 'Int'
    name: 'String'
    orders: 'Order'
    phone: 'String'
  }
  Mutation: { // field return type name
    createClient: 'Client'
    deleteClient: 'Client'
    updateClient: 'Client'
  }
  Order: { // field return type name
    address: 'String'
    dateTime: 'String'
    food: 'String'
    id: 'Int'
  }
  Query: { // field return type name
    queryAllClient: 'Client'
    queryOneClient: 'Client'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createClient: { // args
      email: string; // String!
      name: string; // String!
      phone: string; // String!
    }
    deleteClient: { // args
      id: number; // Int!
    }
  }
  Query: {
    queryAllClient: { // args
      page: number | null; // Int
    }
    queryOneClient: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}