//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "hobbit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub home_planet: String,
}

impl ActiveModelBehavior for ActiveModel {}

