[default]
port = 8000
address = "0.0.0.0"
keep_alive = 5
log_level = "normal"
cli_colors = true

[debug]
port = 8000
address = "127.0.0.1"
keep_alive = 0
log_level = "debug"

[release]
port = 8000
address = "0.0.0.0"
keep_alive = 5
log_level = "critical"
